version: '3.8'

services:
  app:
    container_name: rms_v1
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn config.wsgi:application
      -c gunicorn.conf.py
    restart: unless-stopped
    volumes:
      - './media:/code/media:rw'
      - '/var/log/restaurant-management/logs:/code/logs:rw'
      - '/srv/www/restaurant-management/static:/srv/www/restaurant-management/static:rwx'
      - '/srv/www/restaurant-management/media:/srv/www/restaurant-management/media:rwx'
    ports:
      - "8000:8000"
